# group 名称
name: "AgentGroup1"
# 对 group 的详细描述
description: "智能体组1"
# group 要完成的任务
task: ""

# group 内包含的 agent
agents:
  - Agent1: "config/Agent1.yaml"

# 信息流开始的 agent
start_agent: Agent1

# 路由
routes: []

# 最大执行步数
max_step: 100

# 执行上下文参数
params:
  - name: "number1"
    type: "str"
  - name: "number2"
    type: "str"
  - name: "true_result"
    type: "str"

# 执行上下文结果
results:
  - name: "result"
    type: "str"
  - name: "bool_result"
    type: "str"


# group 场景下的 prompt
prompts:

# 初始化时需要的额外参数
init_extra_params:

# group 提供的工具
tools:

# 其他参数
ifLeaf: True
ifService: False
runtimeRevisionNumber: 1
ifKnowledgeable: True
historyNumber: 0
energy: 0
