# 对外暴露的 id，用于将 agent 引入 group
ref_id: "Agent1"

# agent 的名称
name: "Agent1"
# 对 agent 的详细描述
description: "智能体1"
# agent 角色扮演相关？
role: "Agent1"
# agent 要执行的任务
task: ""
# agent 加载模式
load_type: "module"
# agent 类的位置
loadModule: "agent"
loadClass: "Agent1"

model: "gpt-3.5-turbo"

# 执行上下文参数
params:
  - name: "number1"
    type: "str"
  - name: "number2"
    type: "str"
  - name: "true_result"
    type: "str"

# 执行上下文结果
results:
  - name: "result"
    type: "str"
  - name: "bool_result"
    type: "str"

# agent 的 prompt
prompts:
  - type: "inline"
    role: "system"
    content: |
      Calculate the sum of two numbers and output the result directly without adding any other characters.
tools:
  - type: "VDB"
    name: "VDB1"

# 其他的一些参数
ifLeaf: True
ifService: False
ifKnowledgeable: True
ifLearnable: False
runtimeRevisionNumber: 1
historyNumber: 0
energy: 0

